name: build

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'LLVM branch'
        required: true
        default: 'main'

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUN_NUM: ${{ github.run_number }}_${{ github.run_attempt }}
  BRANCH: ${{ github.event.inputs.BRANCH }}

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: AutoModality/action-clean@v1
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 64

    - name: prepare env
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev libncurses5 python3
        sudo apt -y install bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev libstdc++-$(apt list libstdc++6 2>/dev/null | grep -Eos '[0-9]+\.[0-9]+\.[0-9]+' | head -1 | cut -d . -f 1)-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev zstd

    - name: do the build
      run: bash build.sh
      continue-on-error: true
